<style>
    
    .span12{
        height:350px;

        margin-bottom:20px;
        border-bottom:3px solid #942a25;
    }
    .span12 h6{       
        height:20px;
        background-color: #942a25;
        color:white;
        padding:5px;
        padding-right: 0;
        margin-top:0px;
        border-radius:0px 10px 0px 10px;
    }
    .span12 h2{
        margin-top:50px;
        color: #942a25;
        margin-bottom:-15px;
    }
    .span12 a:hover
    {
        color: #942a25;
        text-decoration: underline;
        cursor:pointer;
    }   

    .span12 h4,.span12 p
    {
        text-indent: 20px;
    }
    .span12 p{
        margin-top:50px;
    }
    
    .span12 h5{
        margin-top:-10px;
        margin-bottom:-10px;
    }
    .noborder
    {
        border:0;
    }
</style>


<div class="row-fluid">
    <div class="span12">
        <h6><?php echo $this->noticia->getCategorianoticia_fk()->getCategorianome(); ?></h6>
        <h2><?php echo $this->noticia->getTitulo(); ?></h2>
        <hr>
        <h5>Data de publicação: <?php echo $this->noticia->getPublicacao() ?></h5>
        <hr>
        <p>
            <?php echo nl2br($this->noticia->getTexto()); ?>
        </p>

    </div>



</div>
